// [move sequence in SAN, french name]
const OPENINGS: [string, string][] = [
  // ── e4 ──────────────────────────────────────────────────────────────────
  ['e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O', 'Ruy Lopez, variante principale'],
  ['e4 e5 Nf3 Nc6 Bb5 a6 Ba4', 'Ruy Lopez, variante Morphy'],
  ['e4 e5 Nf3 Nc6 Bb5 Nf6', 'Ruy Lopez, variante Berlin'],
  ['e4 e5 Nf3 Nc6 Bb5 Bc5', 'Ruy Lopez, variante Cordel'],
  ['e4 e5 Nf3 Nc6 Bb5 d6', 'Ruy Lopez, variante Steinitz'],
  ['e4 e5 Nf3 Nc6 Bc4 Bc5 c3', 'Giuoco Piano, variante classique'],
  ['e4 e5 Nf3 Nc6 Bc4 Bc5', 'Giuoco Piano'],
  ['e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5', 'Attaque des Deux Cavaliers'],
  ['e4 e5 Nf3 Nc6 Bc4 Nf6', 'Défense des Deux Cavaliers'],
  ['e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5', 'Partie Écossaise, variante Ghulam-Kassim'],
  ['e4 e5 Nf3 Nc6 d4 exd4 Nxd4', 'Partie Écossaise'],
  ['e4 e5 Nf3 Nc6 d4 exd4', 'Gambit Écossais accepté'],
  ['e4 e5 Nf3 Nc6 d4', 'Gambit Écossais'],
  ['e4 e5 Nf3 Nc6 Bb5', 'Partie Espagnole (Ruy Lopez)'],
  ['e4 e5 Nf3 Nc6 Bc4', 'Partie Italienne'],
  ['e4 e5 Nf3 Nc6 f4', 'Partie des Trois Cavaliers'],
  ['e4 e5 Nf3 Nf6', 'Partie Russe (Défense Petrov)'],
  ['e4 e5 Nf3 d6', 'Défense Philidor'],
  ['e4 e5 Nf3 f5', 'Contre-gambit Latvian'],
  ['e4 e5 Nc3 Nc6 f4', 'Gambit du Centre'],
  ['e4 e5 Nc3 Nc6 Bc4', 'Partie de Vienne, variante Mieses'],
  ['e4 e5 Nc3 Bc5', 'Partie de Vienne'],
  ['e4 e5 Nc3', 'Ouverture de Vienne'],
  ['e4 e5 f4 exf4 Nf3', 'Gambit du Roi, variante chevalier'],
  ['e4 e5 f4 exf4 Bc4', 'Gambit du Roi, Bc4'],
  ['e4 e5 f4 exf4', 'Gambit du Roi accepté'],
  ['e4 e5 f4 Bc5', 'Gambit du Roi refusé'],
  ['e4 e5 f4', 'Gambit du Roi'],
  ['e4 e5 Nf3', 'Ouverture du Cavalier du Roi'],
  ['e4 e5 d4 exd4', 'Centre Game'],
  ['e4 e5', 'Partie Ouverte (1.e4 e5)'],
  // Sicilienne
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6', 'Défense Sicilienne, Najdorf'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6', 'Sicilienne, Dragon'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6', 'Sicilienne, Scheveningen'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3', 'Sicilienne ouverte'],
  ['e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6', 'Sicilienne, Kan'],
  ['e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6', 'Sicilienne, Accéléré du Dragon'],
  ['e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3', 'Sicilienne classique'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4', 'Sicilienne ouverte'],
  ['e4 c5 c3 d5', 'Sicilienne Alapin, 2…d5'],
  ['e4 c5 c3', 'Sicilienne, attaque Alapin'],
  ['e4 c5 Nc3 Nc6', 'Sicilienne, variante fermée'],
  ['e4 c5 f4', 'Grand Prix Attack'],
  ['e4 c5 Nf3 e6', 'Sicilienne, variante Kan'],
  ['e4 c5', 'Défense Sicilienne'],
  // Française
  ['e4 e6 d4 d5 Nc3 Bb4', 'Française, variante Winawer'],
  ['e4 e6 d4 d5 Nd2 Nf6', 'Française, variante Tarrasch'],
  ['e4 e6 d4 d5 e5 c5', 'Française, variante d\'avance'],
  ['e4 e6 d4 d5 e5', 'Française, variante d\'avance'],
  ['e4 e6 d4 d5 Nc3', 'Française, variante classique'],
  ['e4 e6 d4 d5 exd5', 'Française, variante d\'échange'],
  ['e4 e6 d4 d5', 'Défense Française, variante principale'],
  ['e4 e6', 'Défense Française'],
  // Caro-Kann
  ['e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5', 'Caro-Kann, variante classique'],
  ['e4 c6 d4 d5 e5', 'Caro-Kann, variante d\'avance'],
  ['e4 c6 d4 d5 Nc3', 'Caro-Kann, variante principale'],
  ['e4 c6 d4 d5 exd5', 'Caro-Kann, variante d\'échange'],
  ['e4 c6 d4 d5', 'Caro-Kann, variante principale'],
  ['e4 c6', 'Défense Caro-Kann'],
  // Autres défenses e4
  ['e4 d5 exd5 Qxd5 Nc3 Qa5', 'Scandinave, variante moderne'],
  ['e4 d5 exd5 Qxd5 Nc3', 'Scandinave, 3.Nc3'],
  ['e4 d5 exd5 Nf6', 'Scandinave, variante du cavalier'],
  ['e4 d5 exd5', 'Défense Scandinave acceptée'],
  ['e4 d5', 'Défense Scandinave'],
  ['e4 Nf6 e5 Nd5 d4 d6', 'Défense Alekhine, variante classique'],
  ['e4 Nf6', 'Défense Alekhine'],
  ['e4 d6 d4 Nf6 Nc3 g6', 'Défense Pirc, variante classique'],
  ['e4 d6 d4 Nf6', 'Défense Pirc'],
  ['e4 g6 d4 Bg7', 'Défense Moderne'],
  ['e4 g6', 'Défense Moderne'],
  ['e4 Nc6', 'Défense Nimzowitsch'],
  ['e4 b6', 'Défense Owen'],
  ['e4', 'Partie du Roi'],
  // ── d4 ──────────────────────────────────────────────────────────────────
  ['d4 d5 c4 e6 Nc3 Nf6 Bg5', 'Gambit Dame Refusé, variante orthodoxe'],
  ['d4 d5 c4 e6 Nc3 Nf6', 'Gambit Dame Refusé, variante semi-tarrasch'],
  ['d4 d5 c4 e6 Nf3 Nf6', 'Gambit Dame Refusé'],
  ['d4 d5 c4 e6', 'Gambit Dame Refusé'],
  ['d4 d5 c4 dxc4 Nf3', 'Gambit Dame Accepté'],
  ['d4 d5 c4 dxc4', 'Gambit Dame Accepté'],
  ['d4 d5 c4 c6 Nf3 Nf6 Nc3', 'Défense Slave, variante principale'],
  ['d4 d5 c4 c6 Nf3 Nf6', 'Défense Slave'],
  ['d4 d5 c4 c6', 'Défense Slave'],
  ['d4 d5 c4', 'Gambit Dame'],
  ['d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3', 'Défense du Roi Indien, variante principale'],
  ['d4 Nf6 c4 g6 Nc3 Bg7 e4', 'Défense du Roi Indien, quatre pions'],
  ['d4 Nf6 c4 g6 Nc3 Bg7', 'Défense du Roi Indien'],
  ['d4 Nf6 c4 g6 Nc3', 'Défense du Roi Indien'],
  ['d4 Nf6 c4 g6', 'Défense du Roi Indien'],
  ['d4 Nf6 c4 e6 Nc3 Bb4', 'Défense Nimzo-Indienne'],
  ['d4 Nf6 c4 e6 Nf3 b6', 'Défense Dame-Indienne'],
  ['d4 Nf6 c4 e6', 'Défense Indienne Est'],
  ['d4 Nf6 c4 c5 d5 e6', 'Défense Benoni Moderne'],
  ['d4 Nf6 c4 c5', 'Défense Benoni'],
  ['d4 Nf6 c4 f5 Nc3', 'Hollandaise, variante Stonewall'],
  ['d4 f5', 'Défense Hollandaise'],
  ['d4 c5 d5', 'Défense Benoni Moderne'],
  ['d4 d5', 'Partie de la Dame Fermée'],
  ['d4 Nf6', 'Défense Indienne'],
  ['d4 e6', 'Ouverture du Pion Dame'],
  ['d4 c5', 'Défense Benoni'],
  ['d4', 'Partie du Pion Dame'],
  // ── c4 ──────────────────────────────────────────────────────────────────
  ['c4 e5 Nc3 Nf6 Nf3 Nc6', 'Anglaise, variante à quatre cavaliers'],
  ['c4 e5 Nc3 Nf6 g3', 'Anglaise, système du fianchetto'],
  ['c4 e5 Nc3', 'Anglaise, variante symmétrique inversée'],
  ['c4 e5', 'Anglaise, variante e5'],
  ['c4 c5 Nf3 Nf6 Nc3', 'Anglaise, variante symétrique'],
  ['c4 c5', 'Anglaise, variante symétrique'],
  ['c4 Nf6 Nc3 d5', 'Anglaise, contre Nf6'],
  ['c4 e6 Nc3 d5', 'Anglaise, système catalan'],
  ['c4', 'Ouverture Anglaise'],
  // ── Nf3 ─────────────────────────────────────────────────────────────────
  ['Nf3 d5 c4', 'Ouverture Réti'],
  ['Nf3 d5 g3', 'Ouverture Réti, fianchetto'],
  ['Nf3 Nf6 c4 g6', 'Réti, système du roi indien'],
  ['Nf3', 'Ouverture Réti'],
  // ── Autres ──────────────────────────────────────────────────────────────
  ['g3 d5 Bg2', 'Ouverture Benko'],
  ['g3', 'Ouverture du Fianchetto'],
  ['b3 e5 Bb2', 'Ouverture Larsen'],
  ['b3', 'Ouverture Larsen'],
  ['b4 e5 Bb2', 'Ouverture Polonaise'],
  ['b4', 'Ouverture Polonaise (Orangutan)'],
  ['f4 d5 Nf3', 'Ouverture Bird, variante Lasker'],
  ['f4 e5 fxe5', 'Ouverture Bird, From\'s Gambit'],
  ['f4', 'Ouverture Bird'],
  ['d3 e5', 'Système King\'s Indian Attack'],
  ['d3', 'King\'s Indian Attack'],
  ['Nc3 d5', 'Ouverture Van Geet'],
]

export function detectOpening(sanHistory: string[]): string | null {
  if (sanHistory.length === 0) return null
  const sequence = sanHistory.join(' ')
  let bestName: string | null = null
  let bestLen = 0
  for (const [moves, name] of OPENINGS) {
    if ((sequence === moves || sequence.startsWith(moves + ' ')) && moves.length > bestLen) {
      bestLen = moves.length
      bestName = name
    }
  }
  return bestName
}
